### PR TITLE
More benchmarks and better naive code

### PR DESCRIPTION
**Pull request by josevalim**
This pull request benchmarks more scenarios and uses a better "naive" implementation.

The new implementation uses binaries and Erlang/OTP's ability to avoid allocating new binaries. It performs within the same order of magnitude as UniRecover in all benchmarks except one.

The new scenarios consider when the string is valid ASCII, valid Unicode (japanese characters) and also frequently invalid. You will notice UniRecover performs poorly when frequently invalid, using 56672 more memory than the new naive solution.

---

```
$ mix run benchmarking/benchmark.exs
Operating System: macOS
CPU Information: Apple M1 Max
Number of Available Cores: 10
Available memory: 32 GB
Elixir 1.16.0-dev
Erlang 26.0.2

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
reduction time: 0 ns
parallel: 1
inputs: 200KB Valid ASCII, 200KB Very Often Invalid, 207KB JSON Once Invalid, 210KB Valid Unicode
Estimated total run time: 1.87 min

Benchmarking Binary with input 200KB Valid ASCII ...
Benchmarking Binary with input 200KB Very Often Invalid ...
Benchmarking Binary with input 207KB JSON Once Invalid ...
Benchmarking Binary with input 210KB Valid Unicode ...
Benchmarking UniRecover with input 200KB Valid ASCII ...
Benchmarking UniRecover with input 200KB Very Often Invalid ...
Benchmarking UniRecover with input 207KB JSON Once Invalid ...
Benchmarking UniRecover with input 210KB Valid Unicode ...

##### With input 200KB Valid ASCII #####
Name                 ips        average  deviation         median         99th %
UniRecover       1937.10      516.24 μs    ±10.36%      512.08 μs      548.66 μs
Binary            833.40     1199.90 μs     ±8.35%     1145.63 μs     1502.78 μs

Comparison:
UniRecover       1937.10
Binary            833.40 - 2.32x slower +683.67 μs

Memory usage statistics:

Name          Memory usage
UniRecover            40 B
Binary               128 B - 3.20x memory usage +88 B

**All measurements for memory usage were the same**

##### With input 200KB Very Often Invalid #####
Name                 ips        average  deviation         median         99th %
Binary            806.73        1.24 ms     ±1.51%        1.23 ms        1.31 ms
UniRecover        157.10        6.37 ms    ±22.85%        6.15 ms       10.42 ms

Comparison:
Binary            806.73
UniRecover        157.10 - 5.14x slower +5.13 ms

Memory usage statistics:

Name          Memory usage
Binary               128 B
UniRecover       7254120 B - 56672.81x memory usage +7253992 B

**All measurements for memory usage were the same**

##### With input 207KB JSON Once Invalid #####
Name                 ips        average  deviation         median         99th %
UniRecover       1838.19      544.01 μs     ±1.60%      541.71 μs      579.69 μs
Binary            849.26     1177.50 μs     ±1.23%     1173.88 μs     1238.14 μs

Comparison:
UniRecover       1838.19
Binary            849.26 - 2.16x slower +633.49 μs

Memory usage statistics:

Name          Memory usage
UniRecover           296 B
Binary               128 B - 0.43x memory usage -168 B

**All measurements for memory usage were the same**

##### With input 210KB Valid Unicode #####
Name                 ips        average  deviation         median         99th %
UniRecover        1.14 K      879.31 μs     ±1.87%      875.79 μs      924.80 μs
Binary            1.09 K      920.40 μs     ±1.39%      917.08 μs      972.20 μs

Comparison:
UniRecover        1.14 K
Binary            1.09 K - 1.05x slower +41.09 μs

Memory usage statistics:

Name          Memory usage
UniRecover            40 B
Binary               128 B - 3.20x memory usage +88 B

**All measurements for memory usage were the same**
```

### CODE REVIEW

**Comment by josevalim** [comment]
For completeness, here is how I would effectively implement the algorithm:

```elixir
defmodule UniRecover.Benchmark.Simple do
  @dialyzer :no_improper_lists

  @doc """
  Replaces illegal sequences by building a new string with minimal replacement characters.
  """
  def sub(s) when is_binary(s) do
    IO.iodata_to_binary(sub_valid(s, 0, 0, s))
  end

  defp sub_valid(<<cp::utf8, rest::binary>>, size, start, original) do
    sub_valid(rest, size + codepoint_byte_size(cp), start, original)
  end

  defp sub_valid(<<_, rest::binary>>, size, start, original) do
    valid = binary_part(original, start, size)
    [valid | sub_invalid(rest, start + size + 1, original)]
  end

  defp sub_valid(<<>>, size, start, original), do: binary_part(original, start, size)

  defp sub_invalid(<<cp::utf8, rest::binary>>, size, original) do
    ["�" | sub_valid(rest, codepoint_byte_size(cp), size, original)]
  end

  defp sub_invalid(<<_, rest::binary>>, size, original) do
    sub_invalid(rest, size + 1, original)
  end

  defp sub_invalid(<<>>, _size, _original) do
    "�"
  end

  @compile {:inline, codepoint_byte_size: 1}
  defp codepoint_byte_size(cp) when cp <= 0x007F, do: 1
  defp codepoint_byte_size(cp) when cp <= 0x07FF, do: 2
  defp codepoint_byte_size(cp) when cp <= 0xFFFF, do: 3
  defp codepoint_byte_size(_), do: 4
end
```

And here are the results I get:

```
##### With input 200KB Valid ASCII #####
Name                 ips        average  deviation         median         99th %
UniRecover        1.94 K      515.64 μs     ±8.72%      511.71 μs      547.80 μs
Binary            1.35 K      738.33 μs     ±6.31%      736.08 μs      833.49 μs

Comparison:
UniRecover        1.94 K
Binary            1.35 K - 1.43x slower +222.69 μs

Memory usage statistics:

Name          Memory usage
UniRecover            40 B
Binary                40 B - 1.00x memory usage +0 B

**All measurements for memory usage were the same**

##### With input 200KB Very Often Invalid #####
Name                 ips        average  deviation         median         99th %
Binary            354.31        2.82 ms    ±20.38%        2.75 ms        4.61 ms
UniRecover        158.47        6.31 ms    ±21.78%        6.05 ms       10.82 ms

Comparison:
Binary            354.31
UniRecover        158.47 - 2.24x slower +3.49 ms

Memory usage statistics:

Name          Memory usage
Binary             1.53 MB
UniRecover         6.92 MB - 4.53x memory usage +5.39 MB

**All measurements for memory usage were the same**

##### With input 207KB JSON Once Invalid #####
Name                 ips        average  deviation         median         99th %
UniRecover        1.84 K      544.26 μs     ±1.60%      542.21 μs      576.26 μs
Binary            1.78 K      562.25 μs     ±1.46%      560.21 μs      592.55 μs

Comparison:
UniRecover        1.84 K
Binary            1.78 K - 1.03x slower +17.99 μs

Memory usage statistics:

Name          Memory usage
UniRecover           296 B
Binary               120 B - 0.41x memory usage -176 B

**All measurements for memory usage were the same**

##### With input 210KB Valid Unicode #####
Name                 ips        average  deviation         median         99th %
Binary            1.15 K      873.28 μs     ±1.59%      871.54 μs      901.19 μs
UniRecover        1.14 K      877.30 μs     ±1.56%      875.37 μs      903.66 μs

Comparison:
Binary            1.15 K
UniRecover        1.14 K - 1.00x slower +4.03 μs

Memory usage statistics:

Name          Memory usage
Binary                40 B
UniRecover            40 B - 1.00x memory usage +0 B
```

As you can see, it performs quite well, however, I think the best solution would be one that combines both of our approaches.

What is fast in your approach is that you explicitly check for patterns that are invalid. That's the slowest part of my algorithm. What is fast in my approach is that it is recursive and avoids creating tuples, that's the slowest part of your algorithm.

If you can change my code above, in particular this clause:

```
  defp sub_valid(<<cp::utf8, rest::binary>>, size, start, original) do
    sub_valid(rest, size + codepoint_byte_size(cp), start, original)
  end
```

To a clause that precisely matches on invalid patterns and computes the valid/invalid size parts, I think you will have a solution cleaner and faster than the current ones. :)

**Comment by josevalim** [comment]
Actually, I did a double check on your algorithm and I saw that you still had this at the top:

```
  defp find_bad_sequences(<<_::utf8, rest::binary>>, acc) do
    find_bad_sequences(rest, acc)
  end
```

Therefore, I was wrong! What was slow in my algorithm and fast on your was not the matching, because we both do the same matching.

What makes your algorithm fast is this very smart trick that you use where, instead of computing the size as you go, you compute the size to slice based on the _rest_.

If I change my implementation to use the same trick:

```elixir
defmodule UniRecover.Benchmark.Simple do
  @dialyzer :no_improper_lists

  def sub(s) when is_binary(s) do
    IO.iodata_to_binary(sub_valid(s, s))
  end

  defp sub_valid(<<_::utf8, rest::binary>>, original) do
    sub_valid(rest, original)
  end

  defp sub_valid(<<_, rest::binary>>, original) do
    valid = binary_part(original, 0, byte_size(original) - byte_size(rest) - 1)
    [valid | sub_invalid(rest)]
  end

  defp sub_valid(<<>>, original), do: original

  defp sub_invalid(<<_::utf8, rest::binary>> = binary), do: ["�" | sub_valid(rest, binary)]
  defp sub_invalid(<<_, rest::binary>>), do: sub_invalid(rest)
  defp sub_invalid(<<>>), do: "�"
end
```

I get these results:

```
##### With input 200KB Valid ASCII #####
Name                 ips        average  deviation         median         99th %
UniRecover        1.94 K      514.32 μs    ±11.69%      510.42 μs      535.58 μs
Binary            1.94 K      516.15 μs    ±10.41%      511.42 μs      550.97 μs

Comparison:
UniRecover        1.94 K
Binary            1.94 K - 1.00x slower +1.83 μs

Memory usage statistics:

Name          Memory usage
UniRecover            40 B
Binary                40 B - 1.00x memory usage +0 B

**All measurements for memory usage were the same**

##### With input 200KB Very Often Invalid #####
Name                 ips        average  deviation         median         99th %
Binary            238.16        4.20 ms    ±15.97%        4.11 ms        6.48 ms
UniRecover        162.35        6.16 ms    ±10.20%        6.04 ms        9.02 ms

Comparison:
Binary            238.16
UniRecover        162.35 - 1.47x slower +1.96 ms

Memory usage statistics:

Name          Memory usage
Binary             5.34 MB
UniRecover         6.92 MB - 1.30x memory usage +1.58 MB

**All measurements for memory usage were the same**

##### With input 207KB JSON Once Invalid #####
Name                 ips        average  deviation         median         99th %
UniRecover        1.84 K      543.33 μs     ±1.22%      542.25 μs      565.95 μs
Binary            1.84 K      543.34 μs     ±1.56%      540.50 μs      575.04 μs

Comparison:
UniRecover        1.84 K
Binary            1.84 K - 1.00x slower +0.00747 μs

Memory usage statistics:

Name          Memory usage
UniRecover           296 B
Binary               200 B - 0.68x memory usage -96 B

**All measurements for memory usage were the same**

##### With input 210KB Valid Unicode #####
Name                 ips        average  deviation         median         99th %
UniRecover        1.14 K      876.35 μs     ±2.11%      874.65 μs      902.07 μs
Binary            1.14 K      878.81 μs     ±2.33%      875.46 μs      918.40 μs

Comparison:
UniRecover        1.14 K
Binary            1.14 K - 1.00x slower +2.46 μs

Memory usage statistics:

Name          Memory usage
UniRecover            40 B
Binary                40 B - 1.00x memory usage +0 B
```

As you can see, our results are pretty similar now. You can also notice that my implementation for the "very often invalid" got slower and more expensive than the previous one. :) That's because we are building a sub-binary whenever we find an invalid codepoint (which happens when we call `byte_size(rest)`). However, it is still faster than yours since it is recursive and avoid building the tuples.

**Comment by josevalim** [comment]
Btw, feel free to consider all of the snippets above under the MIT license (the same license as this project). You are welcome to use/reuse any part of them.

**Comment by Moosieus** [comment]
Thank you so much!!! :D

One sticking point's that the original comparisons didn't properly handle valid-but-truncated code points. Without going into the Unicode standard's jargon:

- Valid-but-truncated sequences are replaced with 1x "�"
- Everything else's replaced with 1x "�" per byte

I iterated on your implementation in [this livebook](https://github.com/Moosieus/UniRecover/blob/better-methods/notebooks/iterating.livemd) and included it in `benchmark.exs` along with other derived permutations. They're much more grok-able and benchmark better. I reckon I'll sleep on it for a day and pick a winner.

**Comment by josevalim** [comment]
Oh, I see. FWIW I like the new implementation, it looks cleaner to me and it should hopefully perform as well as the current one?

**Comment by josevalim** [comment]
On a second look, I think we can further improve your code:

1. We can make it body recursive
2. All case clauses seem to be equal, so we can remove them. Here is what I got:

```elixir
defmodule SimpleIII do
  def sub(s) when is_binary(s) do
    IO.iodata_to_binary(sub_valid(s, s))
  end

  defp sub_valid(rest, original)

  defp sub_valid(<<_::utf8, rest::binary>>, original) do
    sub_valid(rest, original)
  end

  defp sub_valid(<<rest::binary>>, original) do
    valid = binary_part(original, 0, byte_size(original) - byte_size(rest))
    [valid | sub_invalid(rest)]
  end

  defp sub_valid(<<>>, original), do: original

  defp sub_invalid(<<_::utf8, rest::binary>> = binary), do: sub_valid(rest, binary)

  # 2/3-byte truncated
  defp sub_invalid(<<0b1110::4, _::4, 0b10::2, _::6, n_lead::2, n_rest::6, rest::binary>>)
       when n_lead != 0b10 do
    ["�" | sub_invalid(<<n_lead::2, n_rest::6, rest::binary>>)]
  end

  # 2/4-byte truncated
  defp sub_invalid(<<0b11110::5, _::3, 0b10::2, _::6, n_lead::2, n_rest::6, rest::binary>>)
       when n_lead != 0b10 do
    ["�" | sub_invalid(<<n_lead::2, n_rest::6, rest::binary>>)]
  end

  # 3/4-byte truncated
  defp sub_invalid(
         <<0b11110::5, _::3, 0b10::2, _::6, 0b10::2, _::6, n_lead::2, n_rest::6, rest::binary>>
       )
       when n_lead != 0b10 do
    ["�" | sub_invalid(<<n_lead::2, n_rest::6, rest::binary>>)]
  end

  defp sub_invalid(<<_, rest::binary>>), do: ["�" | sub_invalid(rest)]
  defp sub_invalid(<<>>), do: <<>>
end
```

**Comment by Moosieus** [comment]
Ah - I think you've actually caught a mistake of mine! All cases were adding one replacement character for the sequence, but the default cases should've added one replacement character _per byte_. I've updated the code to reflect that.

There's two conditions those clauses account for:

- Surrogate code points (range U+D800 - U+DFFF) which are reserved for utf-16, and never constitute valid utf-8 code points (relevant in 2/3-byte truncated sequences).
- "Overlong" encodings which are mathematically possible in utf-8 but not allowed by the standard. I've added [`overlong.livemd`](https://github.com/Moosieus/UniRecover/blob/better-methods/notebooks/overlong.livemd) for an interactive reference. 

With that amended I think `Simple_Trunc`, `SimpleIII`, and `SimpleIII_BinAcc` are all correct per the recommended spec. That said I really ought to write some test cases! I endeavored to at one point but fell short of time.

**Comment by Moosieus** [comment]
As an aside, Livebook's awesome :D

I find it an amazing tool for working a problem, documenting/brain-dumping my thought process, and having that to return to as a reference for my future self.

I really hope more folks in the Elixir ecosystem embrace adding livebooks to repos. So often in programming solutions are documented, but less often how their authors came about implementing them.

**Comment by Moosieus** [comment]
I took some time to clean up the benchmarks, making sure each method conformed to the standard.

In an upset, the original, mostly intact `Simple` method's pulled ahead 🤯

I added a case to test for valid ascii bytes before utf-8. That greatly boosted the JSON benchmark and pure ascii test, although the pure Japanese characters took somewhat of a hit.

The real upshot's how BEAM's optimizes the memory usage down to a **constant 128 Bytes in all cases**. Barring any outliers or bugs I haven't found, I hugely favor that. May not the absolute fastest in many cases, but it's extremely stable.

**Comment by josevalim** [comment]
They all performed quite well in benches. So now the cleaner the code, the better!

**Pull request merged**
